format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
\n$character"""

[username]
show_always = true
style_user = "fg:black bg:blue"
format = "[ $user: ](bold $style)"

[directory]
style = "fg:white bg:#292e42"
format = "[ $path ](bold $style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "[](fg:#ff9e64)"
style = "bg:#ff9e64"
format = '[[ $symbol $branch ](bold fg:white bg:default)]($style)'

[git_status]
style = "bg:#394260"
ahead = '[󰛃 $count ](bold #f7768e)'
behind = '[󰛀 $count ](bold #bb9af7)'
untracked = '[󰿠 $count ](bold #414868)'
modified = '[ $count ](bold #e0af68)'
staged = '[ $count ](bold green)'
deleted = "[ $count ](bold red)"
format = '[[($ahead_behind$all_status )](fg:#769ff0 bg:default)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[character]
success_symbol = ' [\$](bold green)'
error_symbol = ' [\$](bold red)'
vimcmd_symbol = ' [\$](bold green)'
vimcmd_replace_one_symbol = ' [\$](bold purple)'
vimcmd_replace_symbol = ' [\$](bold purple)'
vimcmd_visual_symbol = ' [\$](bold yellow)'
