# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$directory\
${custom.git_dirty}\
${custom.git_clean}\
$git_branch\
$git_status\
$cmd_duration\
$fill\
${custom.singlespace}\
$all\
$character"""

[username]
show_always = true
style_user = "fg:black bg:blue"
format = "[ $user: ](bold $style)"

[directory]
read_only = " 󰌾"
style = "fg:white bg:#292e42"
format = "[ [ ](fg:blue bg:#292e42)$path ](bold $style)[ ](bold default default)"
truncation_length = 3
truncation_symbol = "…/"

[cmd_duration]
format = "[took $duration ]($style)"

[git_branch]
always_show_remote = true
symbol = "[](fg:#ff9e64)"
style = "bg:#ff9e64"
format = '[[ $branch ](bold fg:white bg:default)]($style)'

[git_status]
style = "bg:#394260"
ahead = '[󰛃 $count ](bold #f7768e)'
behind = '[󰛀 $count ](bold #bb9af7)'
untracked = '[󰿠 $count ](bold #414868)'
modified = '[ $count ](bold #e0af68)'
staged = '[ $count ](bold green)'
deleted = "[ $count ](bold red)"
format = '[[($ahead_behind$all_status)](fg:#769ff0 bg:default)]($style)'

[character]
success_symbol = ' [\$](bold green)'
error_symbol = ' [\$](bold red)'
vimcmd_symbol = ' [\$](bold green)'
vimcmd_replace_one_symbol = ' [\$](bold purple)'
vimcmd_replace_symbol = ' [\$](bold purple)'
vimcmd_visual_symbol = ' [\$](bold yellow)'

[fill]
symbol = '·'

[custom.git_dirty]
require_repo = true
when = '~/.config/starship/scripts/git_dirty.sh'  
symbol = '[󱓎](bold #ff9e64)'
format = '$symbol'

[custom.git_clean]
require_repo = true
when = '~/.config/starship/scripts/git_clean.sh'  
symbol = '[](bold green)'
format = '$symbol'

[custom.singlespace]
symbol = ' '
when = true
format = '$symbol'

[aws]
symbol = ""
format = "$symbol ($version(-$name)) "

[buf]
symbol = ""
version_format = 'v${raw}'
format = "$symbol ($version(-$name)) "

[c]
style = 'bold 149'
symbol = "[](bold 149)"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"
detect_extensions = ['c', 'h', 'cpp']

[conda]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[crystal]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[dart]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[docker_context]
style = "#2b55ca"
format = "[$symbol ($version(-$name)) ]($style)"

[elixir]
style = "#2b55ca"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[elm]
style = "#2b55ca"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[fennel]
style = "#2b55ca"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[fossil_branch]
symbol = ""
format = "[$symbol ($version(-$name)) ]($style)"

[guix_shell]
symbol = ""
format = "[$symbol ($version(-$name)) ]($style)"

[haskell]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[haxe]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[hg_branch]
symbol = ""
format = "[$symbol ($version(-$name)) ]($style)"

[hostname]
ssh_symbol = ""
format = "[$symbol ($version(-$name)) ]($style)"

[java]
style = 'bold red dimmed'
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[julia]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[kotlin]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[lua]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[memory_usage]
symbol = "󰍛"
format = "[$symbol ($version(-$name)) ]($style)"

[meson]
symbol = "󰔷"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[nim]
symbol = "󰆥"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[nix_shell]
symbol = ""
format = "[$symbol ($version(-$name)) ]($style)"

[nodejs]
style = 'bold green'
not_capable_style = 'bold red'
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[ocaml]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[package]
symbol = "󰏗"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[perl]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[pijul_channel]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[python]
style = 'yellow bold'
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[rlang]
symbol = "󰟔"
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[ruby]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[scala]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[swift]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[zig]
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"

[gradle]
style = 'bold bright-cyan'
symbol = ""
version_format = 'v${raw}'
format = "[$symbol ($version(-$name)) ]($style)"
